/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;
import BLL.ThanhVienBLL;

import hibernate.entity.thanhvien;
import hibernate.entity.thietbi;
import  javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class QuanLyThanhVienFormAdd extends javax.swing.JDialog {
    QuanLyThanhVienForm form;
    private ThanhVienBLL tvBll;

    /**
     * Creates new form QuanLyThanhVienFormAdd
     */
    public QuanLyThanhVienFormAdd(QuanLyThanhVienForm f) {
        initComponents();
        form=f;
        tvBll=new ThanhVienBLL();
    }
    
    private void AddThanhVien() {
        if (checkValid()) {
            //int maTb = Integer.parseInt(txtMa.getText());
            thanhvien tv = new thanhvien();
            //tv.setMaTV(maTv);
            tv.setHoTen(txbTen.getText());
            tv.setKhoa(txbKhoa.getText());
            tv.setNganh(txbNganh.getText());
            tv.setSDT(txbSdt.getText());
            if (tvBll.AddThanhVien(tv) == 1) {
                JOptionPane.showMessageDialog(null, "Thêm thành viên thành công", "Message", JOptionPane.INFORMATION_MESSAGE);
                form.LoadThanhVien(null);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thành viên thất bại", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private boolean checkValid(){
        /**if (txtMa.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Không được để trống Mã thiết bị", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtMa.getText().length() != 7) {
            JOptionPane.showMessageDialog(null, "Mã thiết bị phải có 7 số", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!txtMa.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Mã thiết bị không được chứa ký tự", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tbBll.CheckMaTBExists(Integer.parseInt(txtMa.getText())) > 0) {
            JOptionPane.showMessageDialog(null, "Mã thiết bị đã tồn tại", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }*/
        if (txbTen.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Không được để trống tên thành viên", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txbKhoa.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Không được để trống khoa", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txbNganh.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Không được để trống ngành", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txbSdt.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Không được để trống số điện thoại", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(txbTen.getText().isBlank() || txbKhoa.getText().isBlank()||txbNganh.getText().isBlank()||txbSdt.getText().isBlank()){
            JOptionPane.showMessageDialog(null,"Không được để trống thongo tin!","Message",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(!txbTen.getText().matches(".*\\d.*")){}
        else{
            JOptionPane.showMessageDialog(null,"Tên không được chứa số!","Message",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(!txbSdt.getText().matches("\\d{10}")){
            JOptionPane.showMessageDialog(null,"Số điện thoại phải đủ 10 số","Message",JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txbTen = new javax.swing.JTextField();
        txbKhoa = new javax.swing.JTextField();
        txbNganh = new javax.swing.JTextField();
        txbSdt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("THÊM THÀNH VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Tên Khoa:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Tên thành viên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Tên ngành: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Số điện thoại: ");

        txbTen.setText(" ");

        txbKhoa.setText(" ");

        txbNganh.setText(" ");

        txbSdt.setText(" ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("THÊM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("THOÁT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txbSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addComponent(jButton2)))))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txbTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txbSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        AddThanhVien();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txbKhoa;
    private javax.swing.JTextField txbNganh;
    private javax.swing.JTextField txbSdt;
    private javax.swing.JTextField txbTen;
    // End of variables declaration
}
