/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

import BLL.ThanhVienBLL;
import BLL.ThietBiBLL;
import BLL.ThongTinSDBLL;
import hibernate.entity.thanhvien;
import hibernate.entity.thietbi;
import hibernate.entity.thongtinsd;
import javax.swing.JScrollPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTable;
import javax.swing.JLabel;
import java.awt.Font;
import java.lang.reflect.AccessFlag;
import java.sql.Timestamp;

import javax.swing.JComboBox;
import javax.swing.JButton;
import com.toedter.calendar.JDateChooser;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;
import java.awt.event.ActionListener;

/**
 *
 * @author ankho
 */
public class ThongKeForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyThanhVienForm
     */
    private ThongTinSDBLL ttBLL;
    private ThanhVienBLL tvBLL;
    private ThietBiBLL tbBLL;
	
    public ThongKeForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BasicInternalFrameUI ui  = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        ttBLL = new ThongTinSDBLL();
        tvBLL = new ThanhVienBLL();
        tbBLL = new ThietBiBLL();
        loadTVTable(null);
        loadCombobox();
        loadTBDuocMuonTable(null, null);
        loadTBDangDuocMuonTable(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1035, 665));
        setMinimumSize(new java.awt.Dimension(1035, 665));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1035, 665));

        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	refreshClicked(evt);
            };;});
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Lịch sử vào khu học tập");

        jTable1.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        	},
        	new String[] {
        		"H\u1ECD v\u00E0 T\u00EAn", "Khoa", "Ng\u00E0nh", "Th\u1EDDi gian v\u00E0o"
        	}
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn Khoa--" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn ngành--" }));
        
        

        jDateChooser1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jDateChooser1AncestorResized(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	searchClicked(evt);
            };;});
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tổng số lượt vào:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(340, 340, 340)
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane1)))
                                .addContainerGap())
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                                .addComponent(jButton2)
                                                .addGap(57, 57, 57)
                                                .addComponent(jButton1)
                                                .addGap(58, 58, 58))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thành viên", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1017, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 543, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Vi phạm", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THỐNG KÊ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane2))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(399, 399, 399)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel5 = new javax.swing.JPanel();
        
        JLabel lblLchSVo = new JLabel();
        lblLchSVo.setText("Thiết bị được mượn");
        lblLchSVo.setFont(new Font("Segoe UI", Font.BOLD, 20));
        
        JButton jButton2_1 = new JButton();
        jButton2_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	    loadTBDuocMuonTable(null, null); // Đảm bảo bảng được tải lại với dữ liệu mặc định trước khi tìm kiếm
        	    
        	    String selectedValue = (String) comboBox.getSelectedItem();
        	    DefaultTableModel model = (DefaultTableModel) table.getModel();
        	    model.setRowCount(0); // Xóa tất cả các dòng hiện có trong bảng

        	    int soluong = 0;
//        	    if(selectedValue.equals("Chọn thiết bị")) {
//        	        // Nếu người dùng chọn "Chọn thiết bị", tải lại bảng với dữ liệu mặc định
//        	        loadTBDuocMuonTable(null, null);
//        	    } 
        	    List<thongtinsd> listTTSD = null;
            	List<thietbi> listTB = null;
            	
            			listTTSD = ttBLL.GetAllThongTinSD();
            			listTB = tbBLL.GetAllThietBi();
            			
            	for(thietbi tb : listTB) {
            		int matchingId = 0;
            		for(thongtinsd ttsd : listTTSD) {

            			if(ttsd.getMaTB()== null) continue;
            			if(tb.getMaTB() == ttsd.getMaTB()) {
            				matchingId = 1;
            				break;
            			}
            		}
            		if(matchingId != 0) {
            			continue;
            		}else if(selectedValue.equals(tb.getTenTB())){
            			Object[] row = {
                				tb.getTenTB(),
                				tb.getMaTB()
                		};
            			soluong = soluong + 1;
                		model.addRow(row);
            		}
            	}
//            		thietbi tb = tbBLL.GetThietBiById(tt.getMaTB());	
            	text.setText(Integer.toString(soluong));
        	}
        });
        jButton2_1.setAction(action);
        jButton2_1.setText("Search");
        jButton2_1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        JButton jButton1_1 = new JButton();
        jButton1_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		comboBox.setSelectedIndex(0);
        		loadTBDuocMuonTable(null, null);
        	}
        });
        jButton1_1.setText("Refresh");
        jButton1_1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        JLabel jLabel3_1 = new JLabel();
        jLabel3_1.setText("Tổng số Được mượn:");
        jLabel3_1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        JLabel lblThitBang = new JLabel();
        lblThitBang.setText("Thiết bị đang được mượn");
        lblThitBang.setFont(new Font("Segoe UI", Font.BOLD, 20));
        
        jButton2_2 = new JButton();
        jButton2_2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        	}
        });
        jButton2_2.setText("Search");
        jButton2_2.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        jButton1_2 = new JButton();
        jButton1_2.setText("Refresh");
        jButton1_2.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        text = new JLabel("0");
        text.setFont(new Font("Tahoma", Font.PLAIN, 16));
        
        JScrollPane scrollPane = new JScrollPane();
        
        scrollPane_1 = new JScrollPane();
        
        scrollPane_2 = new JScrollPane();
        
        JLabel jLabel3_1_1 = new JLabel();
        jLabel3_1_1.setText("Tổng số lượt đang mượn:");
        jLabel3_1_1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        lblNewLabel = new JLabel("0");
        lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 16));
                
                comboBox = new JComboBox();
                
                comboBox_1 = new JComboBox();
        
                comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn thiết bị" }));
                
                comboBox_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn thiết bị" }));
                
                JDateChooser dateChooser_2 = new JDateChooser();
                
                JDateChooser dateChooser_1_1 = new JDateChooser();
                
                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5Layout.setHorizontalGroup(
                	jPanel5Layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(jPanel5Layout.createSequentialGroup()
                			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(jPanel5Layout.createSequentialGroup()
                					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                						.addGroup(jPanel5Layout.createSequentialGroup()
                							.addContainerGap(12, Short.MAX_VALUE)
                							.addComponent(jLabel3_1)
                							.addPreferredGap(ComponentPlacement.RELATED)
                							.addComponent(text)
                							.addGap(70)
                							.addComponent(jButton2_1, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                							.addGap(18)
                							.addComponent(jButton1_1))
                						.addGroup(jPanel5Layout.createSequentialGroup()
                							.addContainerGap()
                							.addComponent(lblLchSVo))
                						.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 421, GroupLayout.PREFERRED_SIZE))
                					.addGap(116))
                				.addGroup(jPanel5Layout.createSequentialGroup()
                					.addContainerGap()
                					.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                					.addPreferredGap(ComponentPlacement.RELATED)))
                			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(jPanel5Layout.createSequentialGroup()
                					.addComponent(lblThitBang, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
                					.addPreferredGap(ComponentPlacement.RELATED)
                					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                				.addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
                					.addComponent(scrollPane_2, GroupLayout.PREFERRED_SIZE, 474, GroupLayout.PREFERRED_SIZE)
                					.addGroup(jPanel5Layout.createSequentialGroup()
                						.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                							.addGroup(jPanel5Layout.createSequentialGroup()
                								.addComponent(dateChooser_2, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
                								.addGap(26)
                								.addComponent(dateChooser_1_1, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
                								.addPreferredGap(ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                								.addComponent(comboBox_1, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE))
                							.addGroup(jPanel5Layout.createSequentialGroup()
                								.addComponent(jButton2_2, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                								.addGap(18)
                								.addComponent(jButton1_2)
                								.addPreferredGap(ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                								.addComponent(jLabel3_1_1, GroupLayout.PREFERRED_SIZE, 181, GroupLayout.PREFERRED_SIZE)
                								.addPreferredGap(ComponentPlacement.RELATED)
                								.addComponent(lblNewLabel)))
                						.addGap(13))))
                			.addGap(10))
                );
                jPanel5Layout.setVerticalGroup(
                	jPanel5Layout.createParallelGroup(Alignment.TRAILING)
                		.addGroup(jPanel5Layout.createSequentialGroup()
                			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(jPanel5Layout.createSequentialGroup()
                					.addGap(133)
                					.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                						.addComponent(lblLchSVo, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                						.addComponent(lblThitBang, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
                				.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                			.addPreferredGap(ComponentPlacement.RELATED)
                			.addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
                				.addGroup(jPanel5Layout.createSequentialGroup()
                					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                						.addComponent(dateChooser_1_1, GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                						.addComponent(dateChooser_2, GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                					.addGap(18))
                				.addGroup(jPanel5Layout.createSequentialGroup()
                					.addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
                						.addComponent(comboBox_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                						.addComponent(comboBox, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                					.addPreferredGap(ComponentPlacement.UNRELATED)))
                			.addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
                				.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                					.addComponent(jButton2_1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                					.addComponent(jButton1_1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                					.addComponent(text)
                					.addComponent(jLabel3_1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                				.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                					.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                						.addComponent(jButton1_2, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                						.addComponent(jLabel3_1_1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                						.addComponent(lblNewLabel))
                					.addComponent(jButton2_2, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)))
                			.addPreferredGap(ComponentPlacement.UNRELATED)
                			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                				.addComponent(scrollPane_2, 0, 0, Short.MAX_VALUE)
                				.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE))
                			.addContainerGap())
                );
                
                table_1 = new JTable();
                scrollPane_2.setViewportView(table_1);
                table_1.setModel(new DefaultTableModel(
                	new Object[][] {
                		{null, null, null},
                		{null, null, null},
                	},
                	new String[] {
                		"T\u00EAn thi\u1EBFt b\u1ECB", "Th\u1EDDi \u0111i\u1EC3m m\u01B0\u1EE3n", "Th\u1EDDi \u0111i\u1EC3m tr\u1EA3"
                	}
                ));
                
                table = new JTable();
                scrollPane_1.setViewportView(table);
                table.setModel(new DefaultTableModel(
                	new Object[][] {
                		{null, null, null},
                		{null, null, null},
                	},
                	new String[] {
                		"T\u00EAn thi\u1EBFt b\u1ECB", "M\u00E3 thi\u1EBFt b\u1ECB", "Th\u1EDDi \u0111i\u1EC3m tr\u1EA3"
                	}
                ));
                jPanel5.setLayout(jPanel5Layout);
                
                        jTabbedPane2.addTab("Thiết bị", jPanel5);

        pack();
    }// </editor-fold>
    private void loadCombobox() {
    	ArrayList<String> listkhoa = tvBLL.getListKhoa();
    	ArrayList<String> listnganh = tvBLL.getListNganh();
    	List<thietbi> listthietbi = tbBLL.GetAllThietBi();
    	Set<String> uniqueDevices = new HashSet();
        
    	for(String khoa : listkhoa) {
    		jComboBox1.addItem(khoa);
    	}
    	for(String nganh : listnganh) {
    		jComboBox2.addItem(nganh);
    	}
    	for(thietbi tb : listthietbi) {
    		uniqueDevices.add(tb.getTenTB());
    	}
    	for(String tb : uniqueDevices) {
    		comboBox.addItem(tb);
    	}
    	for(String tb : uniqueDevices) {
    		comboBox_1.addItem(tb);
    	}
    }
    private void loadTVTable(List l) {
    	List<thongtinsd> listTTSD = null;
    	if (l == null)
    		listTTSD = ttBLL.GetAllThongTinSD();
    	else listTTSD = l;
    	DefaultTableModel model = (DefaultTableModel) jTable1.getModel();   
    	model.setRowCount(0);
    	int soluong = 0;
    	for (thongtinsd tt : listTTSD) {
    		thanhvien tv = tvBLL.getById(tt.getMaTV());
    		Object[] row = {
    				tvBLL.GetHoTenByID(tt.getMaTV()),
    				tv.getKhoa(),
    				tv.getNganh(),
    				tt.getTGVao()
    				,
    		};
    		soluong = soluong + 1;
    		model.addRow(row);
    	}
    	jLabel4.setText(Integer.toString(soluong));
    }
    private void searchClicked(java.awt.event.MouseEvent evt) {
    	List<thongtinsd> searchedList = null;
    	String khoa = null;
    	String nganh = null;
    	Date date = jDateChooser1.getDate();
    	if(jComboBox1.getSelectedIndex() != 0) { 
    		khoa = (String) jComboBox1.getSelectedItem();
    	}
    	if (jComboBox2.getSelectedIndex() != 0) {
    		nganh = (String) jComboBox2.getSelectedItem();
    	}
    	searchedList = ttBLL.searchThongTinSD(date, khoa, nganh);
    	loadTVTable(searchedList);
    }
    private void refreshClicked(java.awt.event.MouseEvent evt) {
    	jDateChooser1.setDate(null);
    	jComboBox1.setSelectedIndex(0);
    	jComboBox2.setSelectedIndex(0);
    	loadTVTable(null);
    }
    private void jDateChooser1AncestorResized(java.awt.event.HierarchyEvent evt) {
    }


    private void searchTBClicked(java.awt.event.MouseEvent evt) {
    	
    	 
    	
    }
    
    private void loadTBDuocMuonTable(List lttsd, List ltb) {
    	List<thongtinsd> listTTSD = null;
    	List<thietbi> listTB = null;
    	if (lttsd == null && ltb == null)
    		{
    			listTTSD = ttBLL.GetAllThongTinSD();
    			listTB = tbBLL.GetAllThietBi();
    		}
    	else {
    		listTTSD = lttsd;
    		listTB = ltb;
    	}
    	DefaultTableModel model = (DefaultTableModel) table.getModel();   
    	model.setRowCount(0);
    	int soluong = 0;
    	for(thietbi tb : listTB) {
    		int matchingId = 0;
    		for(thongtinsd ttsd : listTTSD) {

    			if(ttsd.getMaTB()== null) continue;
    			if(tb.getMaTB() == ttsd.getMaTB()) {
    				matchingId = 1;
    				break;
    			}
    		}
    		if(matchingId != 0) {
    			continue;
    		}else {
    			Object[] row = {
        				tb.getTenTB(),
        				tb.getMaTB()
        		};
    			soluong = soluong + 1;
        		model.addRow(row);
    		}
    	}
//    		thietbi tb = tbBLL.GetThietBiById(tt.getMaTB());	
    	text.setText(Integer.toString(soluong));
    }

    private void loadTBDangDuocMuonTable(List l) {
    	List<thongtinsd> listTTSD = null;
    	if (l == null)
    		listTTSD = ttBLL.GetAllThongTinSD();
    	else listTTSD = l;
    	DefaultTableModel model = (DefaultTableModel) table_1.getModel();   
    	model.setRowCount(0);
    	int soluong = 0;
    	Date date = new Date();
    	Timestamp timestampNow = new Timestamp(date.getTime());
    	for (thongtinsd tt : listTTSD) {
    		if(tt.getMaTB() == null) {
    			continue;
    		}
    		if (timestampNow.compareTo(tt.getTGTra()) < 0) {
                thietbi tb = tbBLL.GetThietBiById(tt.getMaTB());
                Object[] row = {
                		tb.getTenTB(),
                		tt.getTGMuon(),
                		tt.getTGTra(),
                };
                soluong = soluong + 1;
                model.addRow(row);
            } else if (timestampNow.compareTo(tt.getTGTra()) > 0) {
                System.out.println("đã qua " + tt.getTGTra());
            }
//    		System.out.println(tt.getTGTra().getClass().getSimpleName());
//    		System.out.println(tt.getTGMuon().getClass().getSimpleName());
    	}
        
        // In ra thời điểm hiện tại
    	lblNewLabel.setText(Integer.toString(soluong));
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private JTable table;
    private JTable table_1;
    private JButton jButton2_2;
    private JButton jButton1_2;
    private JLabel text;
    private JScrollPane scrollPane_1;
    private JScrollPane scrollPane_2;
    private JLabel lblNewLabel;
    private JComboBox comboBox;
    private JComboBox comboBox_1;
    private final Action action = new SwingAction();
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "SwingAction");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
		}
	}
}
